### ISSUE TITLE
Is a cache accessible from another process?

### ISSUE THREAD

**Issue by avostryakov** [pbrady/fastcache#44]
Can I use a cache from another process? Other words, Is it accessible from different python processes?

P.S. Thank you for the great library!

**Comment by pbrady** [comment]
I don't often use multiple processes in python but it looks to me that one has to go through some effort to get them to communicate with one another or share state (see for example [multiprocessing docs](https://docs.python.org/3/library/multiprocessing.html#sharing-state-between-processes) )

Also, as of python 3.5 the standard library ships with a C implementation of lru_cache in functools.  It should be faster than fastcache because it's able to use an internal API to avoid multiple dict lookups.

**Comment by avostryakov** [comment]
Thank you for the answer. I'll close the issue.
